version: '3.8'
services:
  planner_db:
    container_name: planner_db
    image: postgres:14.4-alpine
    ports:
      - 5432:5432
    volumes:
      - ./pg-data/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_USER=imam
      - POSTGRES_HOST_AUTH_METHOD=trust
  planner_backend:
    container_name: planner_backend
    working_dir: /planner
    command: bundle exec rails s -b 0.0.0.0 -p 5000
    entrypoint: ./start.sh
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_HOST=planner_db
      - DB_USER=imam
      - HISTFILE=/planner/.zsh_history
    volumes:
      - ./backend:/planner
    stdin_open: true
    depends_on:
      - planner_db
  planner_frontend:
    container_name: planner_frontend
    build: ./frontend
    stdin_open: true
    command: npm run dev
    volumes:
      - ./frontend:/planner
  planner_nginx:
    image: nginx:1.23-alpine
    container_name: planner_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    stdin_open: true
    depends_on:
      - planner_frontend
      - planner_backend
    stop_grace_period: 1s
